# This will compile the MatrixIteration.cpp
compile:
	g++ -O3 -I/usr/local/cuda-10.2/targets/x86_64-linux/include/ -L/usr/local/cuda-10.2/targets/x86_64-linux/lib/ -o MatrixIteration MatrixIteration.cpp -lOpenCL
execute:
	./MatrixIteration
clean:
	rm -rf *o MatrixIteration

